### ISSUE TITLE
Design pattern and reusable code

### ISSUE THREAD

**Issue by aschulte201** [budgetiser/budgetiser#136]
- [x] general multi picker->use in transaction filter (finished in 1995ed03a59406f1917b6f3762fe72d44810e97a)
- [x] general screen list (done in 122d9655cc2244b1d35f899bedb47b556c10a325 TODO: @aschulte201 in budgets)

**Comment by minerop5000** [comment]
TODO: apply recently used to category selector https://github.com/budgetiser/budgetiser/pull/186

**Comment by minerop5000** [comment]
will be split up
