### ISSUE TITLE
Fix google warnings

### ISSUE THREAD

**Issue by minerop5000** [budgetiser/budgetiser#144]
- [x] increase size of icon selector for account, category, ...
- [x] Icon selector search text non-colored
- [ ] content label
- [ ] min Android Version

**Comment by aschulte201** [comment]
![image](https://github.com/budgetiser/budgetiser/assets/39188057/37efe077-9aaa-4990-9cb0-c6cf0b2cc21e)
![image](https://github.com/budgetiser/budgetiser/assets/39188057/fc8734f4-3105-4de2-bad4-974b808c78af)
![image](https://github.com/budgetiser/budgetiser/assets/39188057/e41d1955-db5a-476e-a8a0-86ded40d8da0)
![image](https://github.com/budgetiser/budgetiser/assets/39188057/ff107d0b-52e0-42fd-a740-b58e640a8450)
![image](https://github.com/budgetiser/budgetiser/assets/39188057/df2fd04f-792c-463c-a75e-a54766665ce7)
