### ISSUE TITLE
Pre-Launch Bericht: Stabilität

### ISSUE THREAD

**Issue by aschulte201** [budgetiser/budgetiser#145]
Change min SDK
Absturz:
![image](https://github.com/budgetiser/budgetiser/assets/39188057/03929fd0-769b-4db9-9e90-2fb4c66110fb)

 java.lang.RuntimeException: Unable to start activity ComponentInfo{de.budgetiser.budgetiser/de.budgetiser.budgetiser.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/de.budgetiser.budgetiser-Wtad1yzwPdl8z8fHOz0sJA==/base.apk", zip file "/data/app/de.budgetiser.budgetiser-Wtad1yzwPdl8z8fHOz0sJA==/split_config.en.apk", zip file "/data/app/de.budgetiser.budgetiser-Wtad1yzwPdl8z8fHOz0sJA==/split_config.x86.apk", zip file "/data/app/de.budgetiser.budgetiser-Wtad1yzwPdl8z8fHOz0sJA==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/de.budgetiser.budgetiser-Wtad1yzwPdl8z8fHOz0sJA==/lib/x86, /data/app/de.budgetiser.budgetiser-Wtad1yzwPdl8z8fHOz0sJA==/base.apk!/lib/x86, /data/app/de.budgetiser.budgetiser-Wtad1yzwPdl8z8fHOz0sJA==/split_config.en.apk!/lib/x86, /data/app/de.budgetiser.budgetiser-Wtad1yzwPdl8z8fHOz0sJA==/split_config.x86.apk!/lib/x86, /data/app/de.budgetiser.budgetiser-Wtad1yzwPdl8z8fHOz0sJA==/split_config.xxhdpi.apk!/lib/x86, /system/lib]]] couldn't find "libflutter.so"

**Comment by minerop5000** [comment]
Fixed by bumping minimum sdk version
