### ISSUE TITLE
Store settings in shared prefs

### ISSUE THREAD

**Issue by aschulte201** [budgetiser/budgetiser#149]
- e.g. filter/sort option from accounts

**Comment by minerop5000** [comment]
also:

![Image](https://github.com/budgetiser/budgetiser/assets/75438446/3bfc7f0f-27bb-4caa-b1da-6ff2a2b8c61a)

**Comment by minerop5000** [comment]
done for account screen in 526741e5ca89a6b29a7466f7810fb3a62dbc3981
new issue for transaction filter
