### ISSUE TITLE
Dynamic temporary data

### ISSUE THREAD

**Issue by aschulte201** [budgetiser/budgetiser#177]
* Add functionalities to addTransaction function:

PARAMS:
    - title
    - description
    - list of accounts (deterministic, looped)
    - list of accounts 2 (deterministic, looped) -> transfers
    - list of categories (deterministic, looped)
    - list of values (deterministic, looped)
    - list of time between transactions (deterministic, looped)
    - number of values

* Provide Enums

**Comment by minerop5000** [comment]
#197
