### ISSUE TITLE
[BUG] Transactions not loading after deleting Category

### ISSUE THREAD

**Issue by jeppard** [budgetiser/budgetiser#184]
**Describe the bug**
The transactions are not loading if a Category with a Transaction is deleted. No Transaction will be loaded if the Transaction with the deleted Category would be displayed

**To Reproduce**
1. Go to Categories and create a Category, e. g. 'Test'
2. Create a Transaction with this Category.
3. Delete the Category with the transaction
4. Go to Transaction overview
5. See error (Transaction loading forever)

**Expected behavior**
Transactions to be displayed, if the Transaction with the deleted Category should be shown can be discussed. I think it should be shown, because the Transaction shouldn't vanish.

**Screenshots**
![Transaction Screen loading indefinetly](https://github.com/budgetiser/budgetiser/assets/35837126/bfd7f93b-27a9-4140-98fb-50495fa5a338)

**Versions**
 - Device: Redmi Note 9 Pro
 - OS: MIUI Global 12.0.2
 - App-Version: 1.3.0

**Additional context**
If Filters are applied to not show the deleted Category the Transactions are shown

**Comment by minerop5000** [comment]
Thanks for the issue.
Should be fixed in version 1.4. You can also fix it by creating a new category.
