### ISSUE TITLE
[Feature Request] Select multiple Categories

### ISSUE THREAD

**Issue by jeppard** [budgetiser/budgetiser#185]
**Problem and Use Case**
On the Transaction Screen, you are able to select one Category and/or Account to display its Transactions via Radio buttons. But if I want to look at transactions from different Categories or Accounts, I can't... :( 

**Expected behavior**
That the radio buttons are not radio buttons but selection boxes, so I can select multiple Categories/Accounts

**Additional context**
Not applicable

**Comment by aschulte201** [comment]
Available in next release
