### ISSUE TITLE
Transaction title overflow

### ISSUE THREAD

**Issue by aschulte201** [budgetiser/budgetiser#190]
**Problem and Use Case**
I do not want to see the full title length at the expense of missing information on account and category. See picture for example.
![SmartSelect_20230726_202322.jpg](https://github.com/budgetiser/budgetiser/assets/39188057/8e4a7b11-741d-4f1f-b53b-210dba3343fe)

**Expected behavior**
Maybe cut text (signaling that it's cut with ... ) so no information is lost.

**Additional context**
-

**Comment by minerop5000** [comment]
Fixed with next release.
TODO: increase padding: 

![Image](https://github.com/budgetiser/budgetiser/assets/75438446/310cd56a-672c-4c24-9774-df899187fff4)
