### ISSUE TITLE
Usage of Provider Builders

### ISSUE THREAD

**Issue by aschulte201** [budgetiser/budgetiser#207]
**Problem and Use Case**
Usage of Provider:

```
 // TODO: choose 
- Provider.of<BudgetModel>(context, listen: false).getAllBudgets(),
- future: BudgetModel().getAllBudgets(),
```

**Additional context**
Could be relevant for caching as the 2nd version is a new instance, and therefore not cached?

**Comment by minerop5000** [comment]
https://stackoverflow.com/questions/58774301/when-to-use-provider-ofx-vs-consumerx-in-flutter

https://docs.flutter.dev/data-and-backend/state-mgmt/simple

=======
result:
use `Provider.of<BudgetModel>(context, listen: false)`   ["better" if listen not required]
or Consumer wrapped arround the futurebuilder 
`Consumer<TransactionModel>(
        builder: (context, model, child) {
          return FutureBuilder`
when used in bigger widget
