### ISSUE TITLE
Hierarchical categories

### ISSUE THREAD

**Issue by minerop5000** [budgetiser/budgetiser#231]
- [x] discuss ui/ux
    - Picker
        - Single
            - Like image below
            - expansion childs via click on element
            - selection ONLY via radio button
            - leaves are directly selected (but still submit via OK ???)
    - Parent selection (Form, Drag&Drop, both) Which category associated with what parents?
        - Select Category form e.g. Row selected via main screen
        - Select parent new parent for Row selected
            - Single Picker
            - Containing all categories, except oneself and below
            - Move oneself and all below (like directory move) into new parent
    - special Display to distinguish parent from child (e.g. in Transaction Screen Items)?
        - ![Image](https://github.com/budgetiser/budgetiser/assets/39188057/bd59ce8d-9a76-4051-b8ff-82f940daca96)
        - front: selected category
        - background: most specific parent, alpha ~0.5, slight offset
    - maximum nested levels?: endless
    - Multiple parents?: NO

- [ ] add ability to select children/parents of category
- [ ] adapt selectors / UI / database / ...

**Comment by aschulte201** [comment]
Idea:


![Image](https://github.com/budgetiser/budgetiser/assets/39188057/f1c22a4b-324c-4144-a49f-f70961b6c7af)
