### ISSUE TITLE
PDF Import with LLM

### ISSUE THREAD

**Issue by Super-T02** [budgetiser/budgetiser#312]
## Problem and Use Case
I have the problem that I want to import my bank account data via PDF files.
An Idea of mine is to use a LLM which gets as input the textified pdf and gnerates a JSON output, which can be used by your system.

## Expected behavior
PDFs of my institute can be simply imported.

## Additional context
With this feature more users will use your tool ;-)

**Comment by minerop5000** [comment]
Out of scope for the current scope of the app:
- local llm with to much space requirements
  - further investigations would be needed if there is an applicable llm available
- online service not in the vision of the app

Feature possible as separate service?
- many on the website as to-json-converter?
